### ISSUE TITLE
[BUG] Formatted code is too expanded

### ISSUE THREAD

**Issue by HomelessCoder** [microsoft/powerquery-formatter#60] opened 2022-09-13 08:47 UTC
**Expected behavior**
The code is formatted and well-readable.

**Actual behavior**
The code is formatted, but not readable or too expanded.

**To Reproduce**
* The code formatted with the previous version:
```
validateUrlScheme =
    (url as text) as text =>
        if (Uri.Parts(url)[Scheme] <> "https") then
            error "Url scheme must be HTTPS"
        else
            url
```
* The code formatted with the recent version:
```
validateUrlScheme = (
        url as text
    ) as text =>
        if (
            Uri.Parts(
                url
            )[
                Scheme
            ] <> "https"
        ) then
            error
                "Url scheme must be HTTPS"
        else
            url
```

**Additional context**
This is a simple example. We have a file with ~250 rows, which has grown to 100%. 
The issue began a few days ago. Not sure when exactly, but I guess on the `powerquery.vscode-powerquery` extension update from 08/09/2022, 16:30:25.
![image](https://user-images.githubusercontent.com/12776808/189853901-e44b0d4a-bd72-445e-80a2-41320205c001.png)

Could you do something with this, please? Would be nice to have some formatting settings at least to disable such an over-extended version.

Thanks!

**Comment by JordanBoltonMN** [comment] 2022-09-13 13:27
Could you give me the exact version of the extension that's being used? You can get the exact version of the extension by bringing up the list of installed extensions and hovering over it: 

![image](https://user-images.githubusercontent.com/17787492/189913164-571ed0ac-aa89-4aa7-aef9-82f22669689d.png)

**Comment by HomelessCoder** [comment] 2022-09-13 13:32
Seems the same as yours - 0.1.44
![image](https://user-images.githubusercontent.com/12776808/189914612-78a4da93-b39e-4155-b422-d7f8c2e93a51.png)

**Comment by JordanBoltonMN** [comment] 2022-09-13 13:39
Strange. It appears that there's something more to it than the sample code provided, because this is how it formats your code as an expression:

`let
    validateUrlScheme = (url as text) as text =>
        if (Uri.Parts(url)[Scheme] <> "https") then
            error "Url scheme must be HTTPS"
        else
            url
in
    1`

And as a section document:

`section foobar;

validateUrlScheme = (url as text) as text =>
    if (Uri.Parts(url)[Scheme] <> "https") then
        error "Url scheme must be HTTPS"
    else
        url;`

Does this match with your experience? It could be that you're code is a snippet of something larger which doesn't give the full context. For example one variable used during formatting is line length, and if it's a snippet it probably had additional indentation.

**Comment by HomelessCoder** [comment] 2022-09-13 13:52
It's a part of the larger code, yes. But I've just created a new file:

![image](https://user-images.githubusercontent.com/12776808/189916947-dddae85e-2771-46a9-81cd-249547b219f5.png)
![image](https://user-images.githubusercontent.com/12776808/189917717-2a728223-7784-482c-8b21-30ec589d2dee.png)

---
The same behavior with a fresh vscode and the only extension installed :(

![image](https://user-images.githubusercontent.com/12776808/189919230-474c53ea-06d1-4a6e-9378-62b462811c59.png)

**Comment by HomelessCoder** [comment] 2022-09-13 17:22
Oh, you're right! Much better now :+1: 
Still, a completely different format compared to the previous version, so I have the whole file changed in git...

I understand that the vscode extension is actively developing, and I appreciate your efforts. But could you clarify if the format/code style will be subject to further big changes? I mean, git tracking is getting a bit confusing, and maybe we should consider stopping using auto-formatting on save for a while.

**Comment by JordanBoltonMN** [comment] 2022-09-19 14:09
We planned one big formatter change, though the non-experimental mode seems to have a regression regarding verticality. I'd recommend using the experimental mode as it's closer to what the intended format is going to be here on out.

**Comment by HomelessCoder** [comment] 2022-09-20 10:29
Ok, thanks!

Do you think it's worth keeping this ticket open to track the progress on the non-experimental mode? If not - I don't mind if you close it.

**Comment by JordanBoltonMN** [comment] 2022-09-29 13:19
I'm going to close it as we'll be making the experimental formatter the default formatter. Thank for bringing the issue up to begin with, it helped us re-prioritize the experimental formatter.

**Closed by JordanBoltonMN** 2022-09-29 13:19 UTC
Labels: bug
